titleCut ["", "BLACK OUT", 0.5];
sleep 3;
player setPos (getPos debug);
disableUserInput true;
playsound "lift";
sleep 9;
disableUserInput false;
player setPos (getPos e2);
titleCut ["", "BLACK IN", 0.5];
};