// Generated by unRap v1.06 by Kegetys

class CfgVehicles {
	class NonStrategic;	// External class reference
	
	class BuiltItems : NonStrategic {};
	
	class TrapItems : NonStrategic {};
	
	class ReammoBox;	// External class reference
	class TKBasicWeapons_EP1; //ext
	class TKBasicAmmunitionBox_EP1;
	class UNBasicWeapons_EP1;
	class UNBasicAmmunitionBox_EP1;

	class SmallAmmoHolder : ReammoBox {
		scope = private;
		vehicleClass = "HardCorps";
		displayName = "Weapon";
		model = "\ca\weapons\AmmoBoxes\Proxy_UsBasicAmmoBox.p3d";

	};

	class RUAmmoHolder : TKBasicAmmunitionBox_EP1 {
		scope = private;
		vehicleClass = "HardCorps";
		displayName = "Weapon";
	};

	class RUWeaponHolder : TKBasicAmmunitionBox_EP1 {
		scope = private;
		vehicleClass = "HardCorps";
		displayName = "Weapon";
	};

	class UNAmmoHolder : UNBasicAmmunitionBox_EP1 {
		scope = private;
		vehicleClass = "HardCorps";
		displayName = "Weapon";
	};

	class UNWeaponHolder : UNBasicWeapons_EP1 {
		scope = private;
		vehicleClass = "HardCorps";
		displayName = "Weapon";
	};

	class WeaponHolderBase : ReammoBox {
		scope = private;
		vehicleClass = "HardCorps";
		displayName = "Weapon";
	};
	
	
	class CardboardBox_DZ : ReammoBox {
		accuracy = 1000;	// accuracy needed to recognize type of this target
		vehicleClass = "HardCorps";
	};
	
	class FoodBox0_DZ : CardboardBox_DZ {
		scope = public;
		displayName = "Food Box";
		model = "\dayz_equip\models\cardboard_box.p3d";
		
		class TransportWeapons {
			class _xx_ItemMatchbox {
				weapon = "ItemMatchbox";
				count = 3;
			};
			
			class _xx_ItemFlashlight {
				weapon = "ItemFlashlight";
				count = 1;
			};
			
			class _xx_ItemKnife {
				weapon = "ItemKnife";
				count = 2;
			};
		};
		
		class transportmagazines {
			class _xx_FoodCanBakedBeans {
				magazine = "FoodCanBakedBeans";
				count = 3;
			};
			
			class _xx_FoodCanSardines {
				magazine = "FoodCanSardines";
				count = 3;
			};
			
			class _xx_FoodCanFrankBeans {
				magazine = "FoodCanFrankBeans";
				count = 3;
			};
			
			class _xx_FoodCanPasta {
				magazine = "FoodCanPasta";
				count = 3;
			};
		};
	};
	
	class MedBox0_DZ : CardboardBox_DZ {
		scope = public;
		displayName = "Medical Box";
		model = "\dayz_equip\models\cardboard_box_med.p3d";
		
		class transportmagazines {
			class _xx_ItemBandage {
				magazine = "ItemBandage";
				count = 6;
			};
			
			class _xx_ItemEpinephrine {
				magazine = "ItemEpinephrine";
				count = 4;
			};
			
			class _xx_ItemMorphine {
				magazine = "ItemMorphine";
				count = 4;
			};
			
			class _xx_ItemBloodbag {
				magazine = "ItemBloodbag";
				count = 2;
			};
			
			class _xx_ItemPainkiller {
				magazine = "ItemPainkiller";
				count = 4;
			};
			class _xx_ItemChloroform {
				magazine = "ItemChloroform";
				count = 4;
			};
		};
	};

	#include "crates\unweapons.hpp"
	#include "crates\ruweapons.hpp"
	#include "crates\unammo.hpp"
	#include "crates\ruammo.hpp"
};
